version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: quiniela_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: QuinielaMundial2026
    ports:
      - "5433:5432"
    volumes:
      - quiniela_postgres_data:/var/lib/postgresql/data

volumes:
  quiniela_postgres_data:
