-- ============================================================
-- Mundial 2026 - Fase de Grupos (72 partidos oficiales FIFA)
-- Fuente: FIFA World Cup 2026 schedule (Jun 11-27, 2026)
-- ============================================================

-- Eliminar predicciones y partidos de fase de grupos
DELETE FROM Partidos WHERE Fase = 'Fase de Grupos';

INSERT INTO Partidos (EquipoLocal, EquipoVisitante, Grupo, Fase, FechaHora, EstadioCiudad, Estado)
VALUES
-- Jornada 1
('México',              'Sudáfrica',              'A', 'Fase de Grupos', '2026-06-11 19:00:00', 'Estadio Ciudad de México, Ciudad de México',           'Pendiente'),
('Corea del Sur',       'Chequia',                'A', 'Fase de Grupos', '2026-06-12 02:00:00', 'Estadio Guadalajara, Guadalajara',                     'Pendiente'),
('Canadá',              'Bosnia y Herzegovina',   'B', 'Fase de Grupos', '2026-06-12 19:00:00', 'Toronto Stadium, Toronto',                             'Pendiente'),
('Estados Unidos',      'Paraguay',               'D', 'Fase de Grupos', '2026-06-13 01:00:00', 'Los Angeles Stadium, Los Angeles',                     'Pendiente'),
('Qatar',               'Suiza',                  'B', 'Fase de Grupos', '2026-06-13 19:00:00', 'San Francisco Bay Area Stadium, Santa Clara',          'Pendiente'),
('Brasil',              'Marruecos',              'C', 'Fase de Grupos', '2026-06-13 22:00:00', 'New York/New Jersey Stadium, East Rutherford',         'Pendiente'),
('Haití',               'Escocia',                'C', 'Fase de Grupos', '2026-06-14 01:00:00', 'Boston Stadium, Boston',                               'Pendiente'),
('Australia',           'Turquía',                'D', 'Fase de Grupos', '2026-06-14 04:00:00', 'BC Place, Vancouver',                                  'Pendiente'),
('Alemania',            'Curazao',                'E', 'Fase de Grupos', '2026-06-14 17:00:00', 'Houston Stadium, Houston',                             'Pendiente'),
('Países Bajos',        'Japón',                  'F', 'Fase de Grupos', '2026-06-14 20:00:00', 'Dallas Stadium, Arlington',                            'Pendiente'),
('Costa de Marfil',     'Ecuador',                'E', 'Fase de Grupos', '2026-06-14 23:00:00', 'Philadelphia Stadium, Philadelphia',                   'Pendiente'),
('Suecia',              'Túnez',                  'F', 'Fase de Grupos', '2026-06-15 02:00:00', 'Estadio Monterrey, Monterrey',                         'Pendiente'),
('España',              'Cabo Verde',             'H', 'Fase de Grupos', '2026-06-15 16:00:00', 'Atlanta Stadium, Atlanta',                             'Pendiente'),
('Bélgica',             'Egipto',                 'G', 'Fase de Grupos', '2026-06-15 19:00:00', 'Seattle Stadium, Seattle',                             'Pendiente'),
('Arabia Saudita',      'Uruguay',                'H', 'Fase de Grupos', '2026-06-15 22:00:00', 'Miami Stadium, Miami',                                 'Pendiente'),
('Irán',                'Nueva Zelanda',          'G', 'Fase de Grupos', '2026-06-16 01:00:00', 'Los Angeles Stadium, Los Angeles',                     'Pendiente'),
('Francia',             'Senegal',                'I', 'Fase de Grupos', '2026-06-16 19:00:00', 'New York/New Jersey Stadium, East Rutherford',         'Pendiente'),
('Irak',                'Noruega',                'I', 'Fase de Grupos', '2026-06-16 22:00:00', 'Boston Stadium, Boston',                               'Pendiente'),
('Argentina',           'Argelia',                'J', 'Fase de Grupos', '2026-06-17 01:00:00', 'Kansas City Stadium, Kansas City',                     'Pendiente'),
('Austria',             'Jordania',               'J', 'Fase de Grupos', '2026-06-17 04:00:00', 'San Francisco Bay Area Stadium, Santa Clara',          'Pendiente'),
('Portugal',            'RD Congo',               'K', 'Fase de Grupos', '2026-06-17 17:00:00', 'Houston Stadium, Houston',                             'Pendiente'),
('Inglaterra',          'Croacia',                'L', 'Fase de Grupos', '2026-06-17 20:00:00', 'Dallas Stadium, Arlington',                            'Pendiente'),
('Ghana',               'Panamá',                 'L', 'Fase de Grupos', '2026-06-17 23:00:00', 'Toronto Stadium, Toronto',                             'Pendiente'),
('Uzbekistán',          'Colombia',               'K', 'Fase de Grupos', '2026-06-18 02:00:00', 'Estadio Ciudad de México, Ciudad de México',           'Pendiente'),
-- Jornada 2
('Chequia',             'Sudáfrica',              'A', 'Fase de Grupos', '2026-06-18 16:00:00', 'Atlanta Stadium, Atlanta',                             'Pendiente'),
('Suiza',               'Bosnia y Herzegovina',   'B', 'Fase de Grupos', '2026-06-18 19:00:00', 'Los Angeles Stadium, Los Angeles',                     'Pendiente'),
('Canadá',              'Qatar',                  'B', 'Fase de Grupos', '2026-06-18 22:00:00', 'BC Place, Vancouver',                                  'Pendiente'),
('México',              'Corea del Sur',          'A', 'Fase de Grupos', '2026-06-19 01:00:00', 'Estadio Guadalajara, Guadalajara',                     'Pendiente'),
('Estados Unidos',      'Australia',              'D', 'Fase de Grupos', '2026-06-19 19:00:00', 'Seattle Stadium, Seattle',                             'Pendiente'),
('Escocia',             'Marruecos',              'C', 'Fase de Grupos', '2026-06-19 22:00:00', 'Boston Stadium, Boston',                               'Pendiente'),
('Brasil',              'Haití',                  'C', 'Fase de Grupos', '2026-06-20 00:30:00', 'Philadelphia Stadium, Philadelphia',                   'Pendiente'),
('Turquía',             'Paraguay',               'D', 'Fase de Grupos', '2026-06-20 03:00:00', 'San Francisco Bay Area Stadium, Santa Clara',          'Pendiente'),
('Países Bajos',        'Suecia',                 'F', 'Fase de Grupos', '2026-06-20 17:00:00', 'Houston Stadium, Houston',                             'Pendiente'),
('Alemania',            'Costa de Marfil',        'E', 'Fase de Grupos', '2026-06-20 20:00:00', 'Toronto Stadium, Toronto',                             'Pendiente'),
('Ecuador',             'Curazao',                'E', 'Fase de Grupos', '2026-06-21 00:00:00', 'Kansas City Stadium, Kansas City',                     'Pendiente'),
('Túnez',               'Japón',                  'F', 'Fase de Grupos', '2026-06-21 04:00:00', 'Estadio Monterrey, Monterrey',                         'Pendiente'),
('España',              'Arabia Saudita',         'H', 'Fase de Grupos', '2026-06-21 16:00:00', 'Atlanta Stadium, Atlanta',                             'Pendiente'),
('Bélgica',             'Irán',                   'G', 'Fase de Grupos', '2026-06-21 19:00:00', 'Los Angeles Stadium, Los Angeles',                     'Pendiente'),
('Uruguay',             'Cabo Verde',             'H', 'Fase de Grupos', '2026-06-21 22:00:00', 'Miami Stadium, Miami',                                 'Pendiente'),
('Nueva Zelanda',       'Egipto',                 'G', 'Fase de Grupos', '2026-06-22 01:00:00', 'BC Place, Vancouver',                                  'Pendiente'),
('Argentina',           'Austria',                'J', 'Fase de Grupos', '2026-06-22 17:00:00', 'Dallas Stadium, Arlington',                            'Pendiente'),
('Francia',             'Irak',                   'I', 'Fase de Grupos', '2026-06-22 21:00:00', 'Philadelphia Stadium, Philadelphia',                   'Pendiente'),
('Noruega',             'Senegal',                'I', 'Fase de Grupos', '2026-06-23 00:00:00', 'New York/New Jersey Stadium, East Rutherford',         'Pendiente'),
('Jordania',            'Argelia',                'J', 'Fase de Grupos', '2026-06-23 03:00:00', 'San Francisco Bay Area Stadium, Santa Clara',          'Pendiente'),
('Portugal',            'Uzbekistán',             'K', 'Fase de Grupos', '2026-06-23 17:00:00', 'Houston Stadium, Houston',                             'Pendiente'),
('Inglaterra',          'Ghana',                  'L', 'Fase de Grupos', '2026-06-23 20:00:00', 'Boston Stadium, Boston',                               'Pendiente'),
('Panamá',              'Croacia',                'L', 'Fase de Grupos', '2026-06-23 23:00:00', 'Toronto Stadium, Toronto',                             'Pendiente'),
('Colombia',            'RD Congo',               'K', 'Fase de Grupos', '2026-06-24 02:00:00', 'Estadio Guadalajara, Guadalajara',                     'Pendiente'),
-- Jornada 3
('Suiza',               'Canadá',                 'B', 'Fase de Grupos', '2026-06-24 19:00:00', 'BC Place, Vancouver',                                  'Pendiente'),
('Bosnia y Herzegovina', 'Qatar',                 'B', 'Fase de Grupos', '2026-06-24 19:00:00', 'Seattle Stadium, Seattle',                             'Pendiente'),
('Escocia',             'Brasil',                 'C', 'Fase de Grupos', '2026-06-24 22:00:00', 'Miami Stadium, Miami',                                 'Pendiente'),
('Marruecos',           'Haití',                  'C', 'Fase de Grupos', '2026-06-24 22:00:00', 'Atlanta Stadium, Atlanta',                             'Pendiente'),
('Chequia',             'México',                 'A', 'Fase de Grupos', '2026-06-25 01:00:00', 'Estadio Ciudad de México, Ciudad de México',           'Pendiente'),
('Sudáfrica',           'Corea del Sur',          'A', 'Fase de Grupos', '2026-06-25 01:00:00', 'Estadio Monterrey, Monterrey',                         'Pendiente'),
('Curazao',             'Costa de Marfil',        'E', 'Fase de Grupos', '2026-06-25 20:00:00', 'Philadelphia Stadium, Philadelphia',                   'Pendiente'),
('Ecuador',             'Alemania',               'E', 'Fase de Grupos', '2026-06-25 20:00:00', 'New York/New Jersey Stadium, East Rutherford',         'Pendiente'),
('Japón',               'Suecia',                 'F', 'Fase de Grupos', '2026-06-25 23:00:00', 'Dallas Stadium, Arlington',                            'Pendiente'),
('Túnez',               'Países Bajos',           'F', 'Fase de Grupos', '2026-06-25 23:00:00', 'Kansas City Stadium, Kansas City',                     'Pendiente'),
('Turquía',             'Estados Unidos',         'D', 'Fase de Grupos', '2026-06-26 02:00:00', 'Los Angeles Stadium, Los Angeles',                     'Pendiente'),
('Paraguay',            'Australia',              'D', 'Fase de Grupos', '2026-06-26 02:00:00', 'San Francisco Bay Area Stadium, Santa Clara',          'Pendiente'),
('Noruega',             'Francia',                'I', 'Fase de Grupos', '2026-06-26 19:00:00', 'Boston Stadium, Boston',                               'Pendiente'),
('Senegal',             'Irak',                   'I', 'Fase de Grupos', '2026-06-26 19:00:00', 'Toronto Stadium, Toronto',                             'Pendiente'),
('Cabo Verde',          'Arabia Saudita',         'H', 'Fase de Grupos', '2026-06-27 00:00:00', 'Houston Stadium, Houston',                             'Pendiente'),
('Uruguay',             'España',                 'H', 'Fase de Grupos', '2026-06-27 00:00:00', 'Estadio Guadalajara, Guadalajara',                     'Pendiente'),
('Egipto',              'Irán',                   'G', 'Fase de Grupos', '2026-06-27 03:00:00', 'Seattle Stadium, Seattle',                             'Pendiente'),
('Nueva Zelanda',       'Bélgica',                'G', 'Fase de Grupos', '2026-06-27 03:00:00', 'BC Place, Vancouver',                                  'Pendiente'),
('Panamá',              'Inglaterra',             'L', 'Fase de Grupos', '2026-06-27 21:00:00', 'New York/New Jersey Stadium, East Rutherford',         'Pendiente'),
('Croacia',             'Ghana',                  'L', 'Fase de Grupos', '2026-06-27 21:00:00', 'Philadelphia Stadium, Philadelphia',                   'Pendiente'),
('Colombia',            'Portugal',               'K', 'Fase de Grupos', '2026-06-27 23:30:00', 'Miami Stadium, Miami',                                 'Pendiente'),
('RD Congo',            'Uzbekistán',             'K', 'Fase de Grupos', '2026-06-27 23:30:00', 'Atlanta Stadium, Atlanta',                             'Pendiente'),
('Argelia',             'Austria',                'J', 'Fase de Grupos', '2026-06-28 02:00:00', 'Kansas City Stadium, Kansas City',                     'Pendiente'),
('Jordania',            'Argentina',              'J', 'Fase de Grupos', '2026-06-28 02:00:00', 'Dallas Stadium, Arlington',                            'Pendiente');
